export const THAI_SEED = {
  "vegetable": "ผัก",
  "very": "มาก",
  "west": "ตะวันตก",
  "apple": "แอปเปิล",
  "egg": "ไข่",
  "market": "ตลาด",
  "rice": "ข้าว",
  "chicken": "ไก่",
  "fish": "ปลา",
  "bread": "ขนมปัง",
  "water": "น้ำ",
  "milk": "นม",
  "coffee": "กาแฟ",
  "tea": "ชา",
  "hello": "สวัสดี",
  "goodbye": "ลาก่อน",
  "please": "กรุณา",
  "thank you": "ขอบคุณ",
  "bathroom": "ห้องน้ำ",
  "money": "เงิน",
  "train": "รถไฟ",
  "bus": "รถบัส",
  "airport": "สนามบิน",
  "hotel": "โรงแรม",
  "family": "ครอบครัว",
  "work": "งาน",
  "shop": "ร้านค้า",
  "buy": "ซื้อ",
  "sell": "ขาย",
  "price": "ราคา",
  "house": "บ้าน",
  "car": "รถ",
  "phone": "โทรศัพท์",
  "computer": "คอมพิวเตอร์",
  "friend": "เพื่อน",
  "school": "โรงเรียน",
  "teacher": "ครู",
  "student": "นักเรียน",
  "book": "หนังสือ",
  "pen": "ปากกา",
  "street": "ถนน",
  "city": "เมือง",
  "country": "ประเทศ",
  "help": "ช่วยเหลือ",
  "love": "รัก",
  "happy": "มีความสุข",
  "sad": "เศร้า",
  "food": "อาหาร",
  "drink": "เครื่องดื่ม",
  "sleep": "นอน",
  "wake up": "ตื่น",
  "eat": "กิน",
  "go": "ไป",
  "come": "มา",
  "read": "อ่าน",
  "write": "เขียน",
  "speak": "พูด",
  "listen": "ฟัง",
  "today": "วันนี้",
  "tomorrow": "พรุ่งนี้",
  "yesterday": "เมื่อวาน",
  "morning": "เช้า",
  "night": "คืน",
  "blue": "สีน้ำเงิน",
  "red": "สีแดง",
  "green": "สีเขียว",
  "big": "ใหญ่",
  "small": "เล็ก",
  "hot": "ร้อน",
  "cold": "เย็น",
  "open": "เปิด",
  "close": "ปิด",
  "start": "เริ่ม",
  "stop": "หยุด",
  "left": "ซ้าย",
  "right": "ขวา",
  "doctor": "หมอ",
  "hospital": "โรงพยาบาล",
  "police": "ตำรวจ",
  "bank": "ธนาคาร",
  "park": "สวนสาธารณะ",
  "store": "ร้าน",
  "time": "เวลา",
  "weather": "อากาศ",
  "beautiful": "สวย",
  "ugly": "ขี้เหร่",
  "mountain": "ภูเขา",
  "river": "แม่น้ำ",
  "ocean": "มหาสมุทร",
  "music": "ดนตรี",
  "movie": "หนัง",
  "game": "เกม",
  "language": "ภาษา",
};

export function backfillThai(items = []) {
  return items.map((it) => {
    if (it.type === "word" || it.type === "phrase") {
      const key = it.term?.toLowerCase().trim();
      if (!it.thai && key && THAI_SEED[key]) {
        return { ...it, thai: THAI_SEED[key] };
      }
    }
    return it;
  });
}

